"""init database

Revision ID: eb83f3b28784
Revises: 92ad21293203
Create Date: 2022-11-04 13:22:42.381281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb83f3b28784'
down_revision = '92ad21293203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('original_title', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('content_rating', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=32), nullable=True),
    sa.Column('audience_rating', sa.FLOAT(), nullable=True),
    sa.Column('user_rating', sa.FLOAT(), nullable=True),
    sa.Column('thumb', sa.String(length=256), nullable=True),
    sa.Column('art', sa.String(length=256), nullable=True),
    sa.Column('studio', sa.String(length=32), nullable=True),
    sa.Column('tagline', sa.String(length=256), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(length=32), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('viewed_episode_count', sa.Integer(), nullable=True),
    sa.Column('season_count', sa.Integer(), nullable=True),
    sa.Column('available_time', sa.String(length=32), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('last_view_time', sa.DateTime(), nullable=True),
    sa.Column('last_rate_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_table('templates')
    op.drop_table('sys_licenses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_licenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('license', sa.TEXT(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=255), nullable=True),
    sa.Column('type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('start_date', sa.VARCHAR(length=255), nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_user', sa.VARCHAR(length=32), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license')
    )
    op.create_table('templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('media')
    # ### end Alembic commands ###
